### ISSUE TITLE
Support for getMock

### ISSUE THREAD

**Issue by alex-krash** [maxfilatov/phpuaca#1]
It is more convenient to override methods via 
$Script = $this->getMock(MyClass::mock, ['method']);
Expects support for:
$Script->expects($this->any())->method(AUTOCOMPLETE GOES HERE);

**Comment by maxfilatov** [comment]
New supported methods:

```
PHPUnit_Framework_TestCase::getMock
PHPUnit_Framework_TestCase::getMockClass
PHPUnit_Framework_TestCase::getMockForAbstractClass
PHPUnit_Framework_TestCase::getMockForTrait
```
