### ISSUE TITLE
Prophecy completion for prophecies from setup

### ISSUE THREAD

**Issue by susannemoog** [maxfilatov/phpuaca#20]
Hey,

in my setUp() I have:

`$this->blobRestProxy = $this->prophesize(BlobRestProxy::class);`

and in my test:

`$this->blobRestProxy->createBlockBlob('mycontainer', 'foo/bar', chr(26), Arg::any())->shouldHaveBeenCalled();`

I can't get autocomplete on shouldHaveBeenCalled to work, except when explicitly setting up the prophecy in my test (which kind of defeats the purpose of my class var / setup). Am I missing some magic annotation I have to use?

Thanks,

Susi

**Comment by deeky666** [comment]
Same here.
