### ISSUE TITLE
Incompatible with PHPStorm 2016.1.1

### ISSUE THREAD

**Issue by scflode** [maxfilatov/phpuaca#21]
Today a patch release by Idea was issued. After applying PHPStorm reports that the plugin is incompatible.

Tested with plugin versions 1.2.1 and 1.3.1.

The event log output:

```
4:42:49 PM Plugin Error
           Problems found loading plugins:
           Following plugins are incompatible with current IDE build: PHPUnit Autocomplete Assistant
```

IDE version:

```
PhpStorm 2016.1.1
Build #PS-145.970, built on May 3, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by pdelre** [comment]
+1, in IDEA 2016.1.2.

Also tested with plugin versions 1.2.1 and 1.3.1. And interestingly, upgrading to build 145.\* will downgrade the plugin version to 1.2.1.

![image](https://cloud.githubusercontent.com/assets/1379248/15185241/50384522-1766-11e6-9c5a-42676acc40f6.png)
[source](https://plugins.jetbrains.com/plugin/7722?pr=idea)

```
IntelliJ IDEA 2016.1.2
Build #IU-145.971, built on April 29, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by King2500** [comment]
I think #18 needs to be fixed first.

ping @maxfilatov

**Comment by luchaninov** [comment]
http://stackoverflow.com/questions/37279342/prophecy-autocomplete-in-phpstorm

**Comment by nusphere** [comment]
i tagged a pre-release at my fork - you could use it instead.

https://github.com/shopfe/phpuaca/releases/tag/1.3.2-beta

**Comment by pdelre** [comment]
@shopfe Could you please post a jar on your release page?

**Comment by nusphere** [comment]
@pdelre i will do it tomorrow.

**Comment by nusphere** [comment]
@pdelre the jar file is available, now

**Comment by pdelre** [comment]
Working well for me.

```
IntelliJ IDEA 2016.1.2
Build #IU-145.972, built on May 14, 2016
JRE: 1.8.0_76-release-b162 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
